import type { SkillCheckReport } from "./types";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function statusColor(status: string): string {
  switch (status) {
    case "pass": return "#22c55e";
    case "warn": return "#eab308";
    case "fail": return "#ef4444";
    default: return "#6b7280";
  }
}

function severityColor(severity: string): string {
  switch (severity) {
    case "critical": return "#dc2626";
    case "error": return "#ef4444";
    case "warning": return "#eab308";
    default: return "#6b7280";
  }
}

function starsHtml(count: number): string {
  return "★".repeat(count) + "☆".repeat(5 - count);
}

export function generateHtmlReport(report: SkillCheckReport): string {
  const checksHtml = report.checks.map((check) => {
    const issuesHtml = check.issues.map((issue) => `
      <li style="margin: 4px 0; color: ${severityColor(issue.severity)};">
        <code>${escapeHtml(issue.code)}</code> — ${escapeHtml(issue.message)}
      </li>
    `).join("");

    return `
      <section class="check-card">
        <header>
          <h3>${escapeHtml(check.name)}</h3>
          <span class="badge" style="background: ${statusColor(check.status)}">${check.status.toUpperCase()}</span>
          <span class="score">${check.score}/${check.maxScore}</span>
        </header>
        <ul>${issuesHtml}</ul>
      </section>
    `;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SkillCheck Report — ${escapeHtml(report.name)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    header.hero { text-align: center; padding: 2rem 0; border-bottom: 1px solid #334155; margin-bottom: 2rem; }
    header.hero h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    .meta { color: #94a3b8; font-size: 0.875rem; }
    .summary-box { background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; border: 1px solid #334155; }
    .grade { font-size: 3rem; font-weight: bold; color: #22c55e; }
    .stars { font-size: 1.5rem; color: #eab308; letter-spacing: 2px; }
    .check-card { background: #1e293b; border-radius: 8px; padding: 1rem 1.5rem; margin-bottom: 1rem; border: 1px solid #334155; }
    .check-card header { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.75rem; }
    .check-card h3 { flex: 1; font-size: 1rem; }
    .badge { padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; color: #fff; }
    .score { color: #94a3b8; font-size: 0.875rem; }
    ul { list-style: none; padding-left: 0; }
    code { background: #0f172a; padding: 1px 4px; border-radius: 3px; font-size: 0.8rem; }
    footer { text-align: center; color: #64748b; font-size: 0.75rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #334155; }
  </style>
</head>
<body>
  <div class="container">
    <header class="hero">
      <h1>${escapeHtml(report.name)}</h1>
      <p class="meta">${escapeHtml(report.description)}</p>
      <p class="meta">Source: ${escapeHtml(report.source)} · ${new Date(report.createdAt).toLocaleString()}</p>
    </header>

    <div class="summary-box">
      <div style="display: flex; align-items: center; gap: 2rem; justify-content: center;">
        <div class="grade">${report.grade}</div>
        <div>
          <div class="stars">${starsHtml(report.stars)}</div>
          <p>${report.overallScore}/${report.maxScore} points</p>
        </div>
      </div>
      <p style="text-align: center; margin-top: 1rem; color: #94a3b8;">${escapeHtml(report.summary)}</p>
    </div>

    ${checksHtml}

    <footer>Generated by SkillCheck · Agent Skills Quality Dashboard</footer>
  </div>
</body>
</html>`;
}
